name: build-and-deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_PAT_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '10'
      - name: Clone and Build
        run: |
          npm install
          npm install -g gulp-cli
          .github/scripts/check.sh
          gulp build
      - uses: actions/upload-artifact@v2
        with:
          name: website-build
          path: |
              build
  deploy:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_PAT_TOKEN }}
      COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
    needs: [ build ]
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: website-build
          path: /tmp/website-build
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Deploy website
        if: github.event_name == 'push'
        run: |
          git config --global user.name SymbiFlow
          git config --global user.mail robot@mith.ro
          git config --global push.default simple
          .github/scripts/deploy-clone.sh
          cp -a /tmp/website-build/* build
          ./.github/scripts/deploy-push.sh
